version: '3.4'

services:
  db:
    image: postgres:latest
    restart: on-failure
    volumes:
      - postgresql_db_data:/var/lib/postgresql/data/
    env_file:
      - .env
    expose:
      - 5432

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  backend_app:
    build: .
    restart: always
    command: sh -c "alembic upgrade head && 
                    uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend/:/usr/backend/
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgresql_db_data: