"""new

Revision ID: ac734b68c3e1
Revises: 45a37e6c402a
Create Date: 2023-08-30 10:57:43.665318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac734b68c3e1'
down_revision: Union[str, None] = '45a37e6c402a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domain', 'ttttt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('ttttt', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
